# COMMON APPLICATION PROPERTIES
server:
  shutdown: graceful

spring:
  sql:
    init:
      schema-locations: classpath*:db/hsqldb/schema.sql
      data-locations: classpath*:db/hsqldb/data.sql
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    config:
      allow-override: true
      override-none: true
    loadbalancer:
      ribbon:
        enabled: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

# Eureka Configuration
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}
  client:
    registerWithEureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      default:
        maxAttempts: 3
        waitDuration: 1000
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1

# Logging
logging:
  level:
    org.springframework: INFO
    org.springframework.cloud.netflix.eureka: INFO
    com.netflix.discovery: INFO
    com.netflix.eureka: INFO

# Service Timeouts
spring:
  cloud:
    loadbalancer:
      cache:
        ttl: 5s
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1500
        multiplier: 1.5
        max-attempts: 6
        max-interval: 4000

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/petclinic?useSSL=false
    username: root
    password: petclinic
  sql:
    init:
      schema-locations: classpath*:db/mysql/schema.sql
      data-locations: classpath*:db/mysql/data.sql
      mode: ALWAYS