vets:
  cache:
    ttl: 60
    heap-size: 100
---
spring:
  config:
    activate:
      on-profile: default

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://discovery-server:8761/eureka/}

  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

management:
  zipkin:
    tracing:
      endpoint: http://tracing-server:9411/api/v2/spans
